Desenvolvimento/WCM/WCM/Models/Servico.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace WCM.Models
{
    public class Servico
    {
        //Declatação de atributos
        private int cod;
        private string servico_a_executar;
        private double precoBase;
        private int tempoMedio;
        //Propriedades dos atributos
        [Display(Name = "SERVIÇO A EXECUTAR")]
        public string Servico_a_executar
        {
            get
            {
                return servico_a_executar;
            }

            set
            {
                servico_a_executar = value;
            }
        }
        [Display(Name = "PREÇO BASE")]
        public double PrecoBase
        {
            get
            {
                return precoBase;
            }

            set
            {
                precoBase = value;
            }
        }
        [Display(Name = "TEMPO MÉDIO")]
        public int TempoMedio
        {
            get
            {
                return tempoMedio;
            }

            set
            {
                tempoMedio = value;
            }
        }
        [Display(Name = "CÓDIGO")]
        public int Cod
        {
            get
            {
                return cod;
            }

            set
            {
                cod = value;
            }
        }

        internal string Inserir()
        {
            //Declarando string de resposta
            string res = "Inserido com sucesso!";

            try
            {
                Home.con.Open();
                MySqlCommand query =//Query executa uma inserção de um serviço no banco de dados
                    new MySqlCommand("INSERT INTO Servico VALUES(@servico_a_executar,null, @precoBase, @tempoMedio)", Home.con);
                //Passagem de parâmetros
                query.Parameters.AddWithValue("@servico_a_executar", Servico_a_executar);
                query.Parameters.AddWithValue("@precoBase", PrecoBase);
                query.Parameters.AddWithValue("@tempoMedio", TempoMedio);

                //Executa o comando SQL
                query.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                //Passa a exceção para a string de retorno
                res = e.Message.ToString();
            }
            //Testa se a conexão com o banco de dados está aberta e fecha
            if (Home.con.State == System.Data.ConnectionState.Open)
                Home.con.Close();
            //Retorna a resposta
            return res;
        }

        internal string Editar()
        {
            //Declarando string de resposta
            string res = "Inserido com sucesso!";

            try
            {
                Home.con.Open();
                MySqlCommand query =//Query executa uma inserção de um Usuario no banco de dados
                    new MySqlCommand("UPDATE Servico SET servico_a_executar = @servico_a_executar, precoBase = @precoBase, tempoMedio= @tempoMedio WHERE cod = @cod", Home.con);
                //Passagem de parâmetros
                query.Parameters.AddWithValue("@servico_a_executar", Servico_a_executar);
                query.Parameters.AddWithValue("@precoBase", PrecoBase);
                query.Parameters.AddWithValue("@tempoMedio", TempoMedio);
                query.Parameters.AddWithValue("@cod", Cod);


                query.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                //Passa a exceção para a string de retorno
                res = e.Message.ToString();
            }
            //Testa se a conexão com o banco de dados está aberta e fecha
            if (Home.con.State == System.Data.ConnectionState.Open)
                Home.con.Close();
            //Retorna a resposta
            return res;
        }
        //Busca o código do serviçio pelo nome
        public static int BuscaCodServico(string servico)
        {
            int cod = -1;
            try
            {
                //Abre a conexão com o banco de dados
                Home.con.Open();
                MySqlCommand query =//Query seleciona o Usuario quando tem a matricula especificada
                    new MySqlCommand("SELECT * FROM Servico WHERE servico_a_executar = @servico", Home.con);
                //Passagem de parâmetro
                query.Parameters.AddWithValue("@servico", servico);
                //Declarando o leitor
                MySqlDataReader leitor = query.ExecuteReader();

                //Lendo os dados do banco e passando para o objeto
                while (leitor.Read())
                {
                    cod = int.Parse(leitor["cod"].ToString());
                }
            }
            catch (Exception e)
            {
                return -1;
            }
            //Testa se a conexão com o banco de dados está aberta e fecha
            if (Home.con.State == ConnectionState.Open)
                Home.con.Close();
            //Retorna o objeto usuario buscado
            return cod;
        }
        //Busca o serviço pelo código
        public static Models.Servico BuscaServico(int cod)
        {
            //Criando um objeto de serviço
            Servico v = new Servico();
            try
            {
                //Abre a conexão com o banco de dados
                Home.con.Open();
                MySqlCommand query =
                    new MySqlCommand("SELECT * FROM Servico WHERE cod = @cod", Home.con);
                //Passagem de parâmetro
                query.Parameters.AddWithValue("@cod", cod);
                //Declarando o leitor
                MySqlDataReader leitor = query.ExecuteReader();

                //Lendo os dados do banco e passando para o objeto
                while (leitor.Read())
                {
                    v.Servico_a_executar = leitor["servico_a_executar"].ToString();
                    v.PrecoBase = double.Parse(leitor["precoBase"].ToString());
                    v.TempoMedio = int.Parse(leitor["tempoMedio"].ToString());
                    v.Cod = int.Parse(leitor["cod"].ToString());


                }
            }
            catch (Exception e)
            {
                //Como o método retorna um objeto
                //Quando acontece uma exceção é passado null para ele
                v = null;
            }
            //Testa se a conexão com o banco de dados está aberta e fecha
            if (Home.con.State == ConnectionState.Open)
                Home.con.Close();
            //Retorna o objeto usuario buscado
            return v;
        }
        //Lista os serviços com todos os dados
        public static List<Servico> ListaServico()
        {
            //Declarando lista de objetos de Usuario
            List<Servico> servico = new List<Servico>();

            try
            {
                //Abre a conexão com o banco de dados
                Home.con.Open();
                MySqlCommand query =//Query seleciona o Usuario quando estão ativos e tem um tipo de usuario ou outro
                  new MySqlCommand("SELECT * FROM Servico", Home.con);

                //Declarando leitor
                MySqlDataReader leitor = query.ExecuteReader();

                //Lendo os dados dos Usuarios
                while (leitor.Read())
                {
                    //Criando objeto de usuário e passando seus atributos do banco
                    Servico serv = new Servico();
                    serv.Servico_a_executar = leitor["servico_a_executar"].ToString();
                    serv.PrecoBase = double.Parse(leitor["precoBase"].ToString());
                    serv.TempoMedio = int.Parse(leitor["tempoMedio"].ToString());
                    serv.Cod = int.Parse(leitor["cod"].ToString());

                    //Adicionando o Usuario a lista
                    servico.Add(serv);
                }
            }
            catch (Exception e)
            {
                //Como o retorno do método é uma lista de usuários
                //No caso de exceção é passado uma lista vazia
                servico = new List<Servico>();
            }
            //Abre a conexão com o banco de dados
            if (Home.con.State == ConnectionState.Open)
                Home.con.Close();
            //Retorna a lsita de usuarios
            return servico;
        }
        //Lista os nomes dos serviços
        public static List<string> ListaNomeServico()
        {
            //Declarando lista de objetos de Usuario
            List<string> servico = new List<string>();

            try
            {
                //Abre a conexão com o banco de dados
                Home.con.Open();
                MySqlCommand query =//Query seleciona o Usuario quando estão ativos e tem um tipo de usuario ou outro
                  new MySqlCommand("SELECT * FROM Servico", Home.con);

                //Declarando leitor
                MySqlDataReader leitor = query.ExecuteReader();

                //Lendo os dados dos Usuarios
                while (leitor.Read())
                {
                    //Adicionando o Usuario a lista
                    servico.Add(leitor["servico_a_executar"].ToString());
                }
            }
            catch (Exception e)
            {
                //Como o retorno do método é uma lista de usuários
                //No caso de exceção é passado uma lista vazia
                servico = new List<string>();
            }
            //Abre a conexão com o banco de dados
            if (Home.con.State == ConnectionState.Open)
                Home.con.Close();
            //Retorna a lsita de usuarios
            return servico;
        }
        internal string Excluir()
        {
            //Declarando string de resposta
            string res = "Salvo com sucesso!";

            try

Desenvolvimento/WCM/WCM/Controllers/ServicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WCM.Models;

namespace WCM.Controllers
{
    public class ServicoController : Controller
    {
        // GET: Servico
        public ActionResult Servico()
        {
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return View();
            else
                return RedirectToAction("Index", "Home");
        }
        [HttpPost]//Cadastra serviço
        public ActionResult Servico(string servico_a_executar, double precoBase, int tempoMedio)
        {
            Servico m = new Servico();

            m.Servico_a_executar = servico_a_executar;
            m.PrecoBase = precoBase;
            m.TempoMedio = tempoMedio;
            TempData["Msg"] = m.Inserir();
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return RedirectToAction("Lista");
            else
                return RedirectToAction("Index", "Home");
        }
        //Lista serviços
        public ActionResult Lista()//retorno da view com os medicos 
        {
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return View("Lista", Models.Servico.ListaServico());
            else
                return RedirectToAction("Index", "Home");
        }
        //Tela de editar
        public ActionResult Editar(int id)
        {
            Servico servico = Models.Servico.BuscaServico(id);
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return View("Editar", servico);
            else
                return RedirectToAction("Index", "Home");
        }
        [HttpPost]//update no serviço
        public ActionResult Editar(Servico servico)
        {
            TempData["Msg"] = servico.Editar();
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return RedirectToAction("Lista");
            else
                return RedirectToAction("Index", "Home");
        }
        //tela excluir
        public ActionResult Excluir(int id)
        {
            TempData["id"] = id;
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return View(Models.Servico.BuscaServico(id));
            else
                return RedirectToAction("Index", "Home");
        }
        [HttpPost]//excluir
        public ActionResult Excluir()
        {
            if (TempData["id"] != null)
            {
                Servico servico = new Servico();
                servico.Cod = int.Parse(TempData["id"].ToString());
                servico.Excluir();
            }
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return RedirectToAction("Lista");
            else
                return RedirectToAction("Index", "Home");
        }

    }
}

Desenvolvimento/WCM/WCM/Views/Servico/Editar.cshtml
@model WCM.Models.Servico

@{
    /**/

    ViewBag.Title = "Editar Serviços";
}
<div class="inner">
    <h2>Editar Serviço</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal fields">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="field half form-group">
                @Html.LabelFor(model => model.Cod, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Cod, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @type = "text" } })
                    @Html.ValidationMessageFor(model => model.Cod, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.Servico_a_executar, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Servico_a_executar, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Servico_a_executar, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.PrecoBase, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PrecoBase, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PrecoBase, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.TempoMedio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TempoMedio, new { htmlAttributes = new { @class = "form-control", @type = "text" } })
                    @Html.ValidationMessageFor(model => model.TempoMedio, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="field half form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Salvar" class="btn btn-default" />
                </div>
            </div>
        </div>
    }


    <div>
        @Html.ActionLink("Voltar para a Lista", "Lista")
    </div>
</div>
@section Script{
    <script>
        //Máscara
        $(document).ready(function () {
            $("#PrecoBase").mask("000.000.00,00");

        });
    </script>
}

Desenvolvimento/WCM/WCM/Views/Servico/Excluir.cshtml
@model WCM.Models.Servico

@{
    /**/

    ViewBag.Title = "Excluir";
}

<h2>Excluir Serviço</h2>

<h3>Você tem certeza que deseja excluir?</h3>
<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Servico_a_executar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Servico_a_executar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecoBase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecoBase)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TempoMedio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TempoMedio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cod)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Voltar para a Lista", "Lista")
        </div>
    }
</div>

Desenvolvimento/WCM/WCM/Views/Servico/Lista.cshtml
@model IEnumerable<WCM.Models.Servico>

@{
    /**/

    ViewBag.Title = "Serviços";
}

@if (TempData["Msg"] != null)
{
    if (TempData["Msg"].ToString().Equals("Inserido com sucesso!"))
    {
        <div id="Esconder" style="text-align:center; background-color: aquamarine"> @TempData["Msg"] </div>
    }
    else
    {
        <div id="Esconder" style="text-align:center; background-color: red"> @TempData["Msg"] </div>
    }
}

<div class="inner">

    <h2>Lista de Serviços</h2>
    <p>
        @Html.ActionLink("Cadastre um Novo", "Servico")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Servico_a_executar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrecoBase)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TempoMedio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cod)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Servico_a_executar)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrecoBase)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TempoMedio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cod)
                </td>

                <td>
                    @*@Html.ActionLink("Cadastre um Serviço", "Servico", "Servico", new { id = item.Cod+ "/" }, null) |*@
                    @Html.ActionLink("Editar", "Editar", "Servico", new { id = item.Cod + "/" }, null) |
                    @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |*@
                    @Html.ActionLink("Excluir", "Excluir", "Servico", new { id = item.Cod + "/" }, null)
                </td>
            </tr>
        }

    </table>
</div>

@section Script{
    <script>
        $(document).ready(function () {
            $('#Esconder').delay(20000).fadeOut();
        });
    </script>
}

Desenvolvimento/WCM/WCM/Views/Servico/Servico.cshtml
@model WCM.Models.Servico

@{
                /**/

                ViewBag.Title = "Cadastro de Serviço";
}
<div class="inner">
    <h2>Cadastrar Serviço</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal fields">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="field half form-group">
                @Html.LabelFor(model => model.Servico_a_executar, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Servico_a_executar, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Servico_a_executar, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.PrecoBase, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PrecoBase, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PrecoBase, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.TempoMedio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TempoMedio, new { htmlAttributes = new { @class = "form-control", type = "text" } })
                    @Html.ValidationMessageFor(model => model.TempoMedio, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                    @Html.LabelFor(model => model.TempoMedio, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TempoMedio, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TempoMedio, "", new { @class = "text-danger" })
                    </div>
                </div>*@
            <div class="field half form-group">
            </div>

            <div class="field half form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div><div>
                    @Html.ActionLink("Voltar para o Serviço", "Lista")
                </div>
            </div>
        </div>
    }


</div>