Desenvolvimento/WCM/WCM/Models/OrdemDeServico.cs
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace WCM.Models
{
    public class OrdemDeServico
    {
        //Declaração das variaveis
        private int ordem, cod;
        private string tanque;
        private string km_rodados;
        private DateTime data_saida, data_entrada;
        private string placa, cpf;

        //Propriedades das variaveis
        [DisplayName("ORDEM")]
        public int Ordem
        {
            get { return ordem; }
            set { ordem = value; }
        }

        [DisplayName("CPF")]
        public string Cpf
        {
            get { return cpf; }
            set { cpf = value; }
        }

        [DisplayName("TANQUE")]
        public string Tanque
        {
            get { return tanque; }
            set { tanque = value; }
        }

        [DisplayName("CÓDIGO")]
        public int Cod
        {
            get { return cod; }
            set { cod = value; }
        }

        [DisplayName("KILÔMETROS RODADOS")]
        public string Km_rodados
        {
            get { return km_rodados; }
            set { km_rodados = value; }
        }

        [DisplayName("DATA DE ENTRADA")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Data_entrada
        {
            get { return data_entrada; }
            set { data_entrada = value; }
        }

        [DisplayName("DATA DE SAÍDA")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Data_saida
        {
            get { return data_saida; }
            set { data_saida = value; }
        }
        [DisplayName("PLACA")]
        public string Placa
        {
            get { return placa; }
            set { placa = value; }
        }

        //Cadastro de Ordem de Serviço
        internal string Cadastrar()
        {
            try
            {
                //Abrindo a conexão com o banco
                Home.con.Open();
                //Fazendo o comando de INSERT colocando os dados de médicos
                MySqlCommand query =
                    new MySqlCommand("INSERT INTO ordem_de_servico VALUES(null,@tanque, @km_rodados, @data_entrada, @data_saida, @placa,@cpf)", Home.con);

                query.Parameters.AddWithValue("@tanque", Tanque);
                query.Parameters.AddWithValue("@km_rodados", Km_rodados);
                query.Parameters.AddWithValue("@data_entrada", Data_entrada);
                query.Parameters.AddWithValue("@data_saida", DateTime.Now.AddDays(15));
                query.Parameters.AddWithValue("@placa", Placa);
                query.Parameters.AddWithValue("@cpf", Cpf);
                //query.Parameters.AddWithValue("@cod", Cod);

                query.ExecuteNonQuery();
            }
            //Caso se der erro
            catch (Exception e)
            {
                //Retorna a mensagem de erro
                return e.Message;
            }

            //Compara se a conexão está aberta, se estiber fecha
            if (Home.con.State == ConnectionState.Open)
                //Fecha conexão
                Home.con.Close();

            return "Inserido com sucesso!";
        }
        //Listar ordens de serviço
        public static List<OrdemDeServico> ListaServico()
        {
            //Declarando lista de objetos de Usuario
            List<OrdemDeServico> ordem = new List<OrdemDeServico>();

            try
            {
                //Abre a conexão com o banco de dados
                Home.con.Open();
                MySqlCommand query =//Query seleciona o Usuario quando estão ativos e tem um tipo de usuario ou outro
                  new MySqlCommand("SELECT * FROM Ordem_de_servico", Home.con);

                //Declarando leitor
                MySqlDataReader leitor = query.ExecuteReader();

                //Lendo os dados dos Usuarios
                while (leitor.Read())
                {
                    //Criando objeto de usuário e passando seus atributos do banco
                    OrdemDeServico serv = new OrdemDeServico();
                    serv.Ordem = int.Parse(leitor["Ordem"].ToString());
                    serv.Tanque = leitor["tanque"].ToString(); 
                    serv.Km_rodados = leitor["km_rodados"].ToString();
                    serv.Data_entrada = (DateTime)leitor["data_entrada"];
                    string teste = leitor["data_saida"].ToString();
                    //Nullable<DateTime> dateNull = null;
                    if (!teste.Equals(""))
                        serv.Data_saida = (DateTime)leitor["data_saida"];
                    else
                        serv.Data_saida = DateTime.Now;
                    serv.Placa = leitor["FK_Veiculo_placa"].ToString();
                    serv.Cpf = leitor["cpf"].ToString();

                    //serv.Cod = int.Parse(leitor["cod"].ToString());

                    //Adicionando o Usuario a lista
                    ordem.Add(serv);
                };
            }
            catch (Exception e)
            {
                //Como o retorno do método é uma lista de usuários
                //No caso de exceção é passado uma lista vazia
                ordem = new List<OrdemDeServico>();
            }
            //Abre a conexão com o banco de dados
            if (Home.con.State == ConnectionState.Open)
                Home.con.Close();
            //Retorna a lsita de usuarios
            return ordem;
        }
        //Editar ordens de serviço
        internal string Editar()
        {
            //Declarando string de resposta
            string res = "Editado com sucesso!";

            try
            {
                Home.con.Open();
                MySqlCommand query =
                    new MySqlCommand("UPDATE  ordem_de_servico SET tanque = @tanque, km_rodados = @km_rodados, data_entrada = @data_entrada, "
                    + " data_saida = @data_saida,cpf = @cpf WHERE ordem = @ordem", Home.con);
                //Passagem de parâmetros
                query.Parameters.AddWithValue("@ordem", Ordem);
                query.Parameters.AddWithValue("@tanque", Tanque);
                query.Parameters.AddWithValue("@km_rodados", Km_rodados);
                query.Parameters.AddWithValue("@data_entrada", Data_entrada);
                query.Parameters.AddWithValue("@data_saida", Data_saida);
                query.Parameters.AddWithValue("@cpf", cpf);

                //Executa o comando SQL
                query.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                //Passa a exceção para a string de retorno
                res = e.Message.ToString();
            }
            //Testa se a conexão com o banco de dados está aberta e fecha
            if (Home.con.State == System.Data.ConnectionState.Open)
                Home.con.Close();
            //Retorna a resposta
            return res;
        }
        //Buscar ordem de serviço específica
        public static OrdemDeServico BuscaOrdemDeServico(int ordem)
        {
            //Criando um objeto de serviço
            OrdemDeServico serv = new OrdemDeServico();
            try
            {
                //Abre a conexão com o banco de dados
                Home.con.Open();
                MySqlCommand query =
                    new MySqlCommand("SELECT * FROM ordem_de_servico WHERE ordem = @ordem", Home.con);
                //Passagem de parâmetro
                query.Parameters.AddWithValue("@ordem", ordem);
                //Declarando o leitor
                MySqlDataReader leitor = query.ExecuteReader();

                //Lendo os dados do banco e passando para o objeto
                while (leitor.Read())
                {
                    serv.Ordem = int.Parse(leitor["ordem"].ToString());
                    serv.Tanque = leitor["tanque"].ToString();
                    serv.Km_rodados = leitor["km_rodados"].ToString();
                    serv.Data_entrada = (DateTime)leitor["data_entrada"];
                    serv.Data_saida = (DateTime)leitor["data_saida"];
                    serv.Placa = leitor["FK_Veiculo_placa"].ToString();
                    serv.Cpf = leitor["cpf"].ToString();

                }
            }
            catch (Exception e)
            {
                //Como o método retorna um objeto
                //Quando acontece uma exceção é passado null para ele
                serv = null;
            }
            //Testa se a conexão com o banco de dados está aberta e fecha
            if (Home.con.State == ConnectionState.Open)
                Home.con.Close();
            //Retorna o objeto usuario buscado
            return serv;
        }
        //Pesquisa a ordem de serviço por qualquer coluna do banco de dados
        public static List<OrdemDeServico> BuscaOrdemDeServico(string parametroQualquer)
        {
            List<OrdemDeServico> lista = new List<OrdemDeServico>();
            try
            {
                //Abre a conexão com o banco de dados
                Home.con.Open();
                MySqlCommand query =
                    new MySqlCommand(" SELECT * FROM Ordem_de_servico WHERE ordem LIKE @parametroQualquer OR tanque LIKE @parametroQualquer OR km_rodados LIKE @parametroQualquer OR data_entrada LIKE @parametroQualquer OR data_saida LIKE @parametroQualquer OR FK_Veiculo_placa LIKE @parametroQualquer OR cpf LIKE @parametroQualquer", Home.con);
                //Passagem de parâmetro
                query.Parameters.AddWithValue("@parametroQualquer", "%" + parametroQualquer + "%");
                //Declarando o leitor
                MySqlDataReader leitor = query.ExecuteReader();

                //Lendo os dados do banco e passando para o objeto

Desenvolvimento/WCM/WCM/Controllers/OrdemDeServicoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WCM.Models;

namespace WCM.Controllers
{
    public class OrdemDeServicoController : Controller
    {
        [HttpPost]//Cadastra
        public ActionResult Cadastrar(OrdemDeServico ordem_de_servico, string listaCpf, string listaPlacas, string tanque)
        {
            ordem_de_servico.Cpf = listaCpf;
            ordem_de_servico.Placa = listaPlacas;
            ordem_de_servico.Tanque = tanque;
            TempData["Msg"] = ordem_de_servico.Cadastrar();
            int id_ordem = ordem_de_servico.BuscaCodOrdem();
            if (id_ordem != -1)
            {
                return RedirectToAction("CadastrarPertence", new { id = id_ordem });
            }
            return RedirectToAction("Lista");
        }
        //Tela de listagem de OS
        public ActionResult Lista()
        {
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return View("Lista", Models.OrdemDeServico.ListaServico());
            else
                return RedirectToAction("Index","Home");
        }
        //Tela de editar
        public ActionResult Editar(int id)
        {
            OrdemDeServico ordem_de_servico = Models.OrdemDeServico.BuscaOrdemDeServico(id);
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return View("Editar", ordem_de_servico);
            else
                return RedirectToAction("Index", "Home");
        }
        [HttpPost]//Efetua o update no banco de dados
        public ActionResult Editar(OrdemDeServico ordem_de_servico)
        {

            TempData["Msg"] = ordem_de_servico.Editar();
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return RedirectToAction("Lista");
            else
                return RedirectToAction("Index", "Home");
        }
        //Tela de Cadastrar
        public ActionResult Cadastrar()
        {
            ViewBag.listaCpf = new SelectList(Usuario.ListaCpfs("Cliente"));
            ViewBag.listaPlacas = new SelectList("123.456.978-65");
            ViewBag.listaServicos = new SelectList(Servico.ListaNomeServico());
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return View();
            else
                return RedirectToAction("Index", "Home");
        }
        //Busca as placas dos veículos de um usuário
        public JsonResult GetPlacas(string CPF)
        {
            return Json(Veiculo.buscaVeiculosDoUsuario(CPF), JsonRequestBehavior.AllowGet);
        }
        //Tela para cadastrar serviços na OS
        public ActionResult CadastrarPertence(int id)
        {
            Pertence pertence = new Pertence();
            pertence.FkOrdem = id;
            Session["fkOrdem"] = id;
            ViewBag.listaServicosDaOrdem = Pertence.BuscaServicosDaOrdem(pertence.FkOrdem);
            ViewBag.listaServicos = new SelectList(Servico.ListaNomeServico());
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return View("CadastrarPertence", pertence);
            else
                return RedirectToAction("Index", "Home");
        }
        //Cadastra o serviço na OS
        public JsonResult CadastrarPertenceJS(double preco)
        {
            Pertence pertence = new Pertence();
            pertence.Preco = preco;
            pertence.FkCod = int.Parse(Session["codServ"].ToString());
            pertence.FkOrdem = int.Parse(Session["fkOrdem"].ToString());
            TempData["Msg"] = pertence.Inserir();
            ViewBag.listaServicosDaOrdem = Pertence.BuscaServicosDaOrdem(pertence.FkOrdem);
            var resultado = new
            {
                listaServicos = ViewBag.listaServicosDaOrdem
            };
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }
        //retorna o código do serviço pelo nome
        public JsonResult BuscarCodServico(string servico)
        {
            int codServico = Servico.BuscaCodServico(servico);
            var resultado = new
            {
                cod = codServico
            };
            Session["codServ"] = codServico;
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }
        //Mostra os detalhes da OS
        public ActionResult Detalhes(int id)
        {
            ViewBag.listaServicosDaOrdem = Pertence.BuscaServicosDaOrdem(id);
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return View("Detalhes",Models.OrdemDeServico.BuscaOrdemDeServico(id));
            else
                return RedirectToAction("Index", "Home");
        }
        //tela de excluir
        public ActionResult Excluir(int id)
        {
            TempData["id"] = id;
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return View(Models.OrdemDeServico.BuscaOrdemDeServico(id));
            else
                return RedirectToAction("Index", "Home");
        }
        [HttpPost]//excluir
        public ActionResult Excluir()
        {
            if (TempData["id"] != null)
            {
                OrdemDeServico ordem = new OrdemDeServico();
                ordem.Ordem = int.Parse(TempData["id"].ToString());
                ordem.Excluir();
            }
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return RedirectToAction("Lista");
            else
                return RedirectToAction("Index", "Home");
        }
        //Tela de buscar
        public ActionResult Buscar()
        {
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return View();
            else
                return RedirectToAction("Index", "Home");
        }
        [HttpPost]//Buscar
        public ActionResult Buscar(string ordem)
        {
            List<OrdemDeServico> listaOrdem = Models.OrdemDeServico.BuscaOrdemDeServico(ordem);
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return View("Lista", listaOrdem);
            else
                return RedirectToAction("Index", "Home");
        }
        //Retorna a ordem do banco
        public JsonResult BuscarOrdem(string ordem)
        {
            return Json(Models.OrdemDeServico.BuscaOrdemDeServico(ordem), JsonRequestBehavior.AllowGet);
        }
    }
}

Desenvolvimento/WCM/WCM/Views/OrdemDeServico/Buscar.cshtml
@model WCM.Models.OrdemDeServico

@{
    /**/

    ViewBag.Title = "Buscar";
}

<h2>Buscar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ordem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ordem, new { htmlAttributes = new { @class = "form-control", @type = "text" } })
                @Html.ValidationMessageFor(model => model.Ordem, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Buscar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para a Lista", "Lista")
</div>

Desenvolvimento/WCM/WCM/Views/OrdemDeServico/Cadastrar.cshtml
 @model WCM.Models.OrdemDeServico

@{
                /**/

                /**/

                ViewBag.Title = "Cadastrar";
}
<div class="inner">
    <h2>Cadastrar Ordem De Servico</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="fields form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="field half form-group">
                @Html.LabelFor(model => model.Cpf, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10" onchange="atualizaPlacas()">
                    @Html.DropDownList("listaCpf", "Selecione o CPF do Cliente")
                    @Html.ValidationMessageFor(model => model.Cpf, "", new { @class = "text-danger", })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("listaPlacas", "Selecione o veículo")
                    @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger", })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.Tanque, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Tanque, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tanque, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.Km_rodados, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Km_rodados, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Km_rodados, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.Data_entrada, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Data_entrada, new { htmlAttributes = new { @class = "form-control", type = "text", minlength = "10", maxlength = "10" } })
                    @Html.ValidationMessageFor(model => model.Data_entrada, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Cadastrar" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("voltar para a lista", "Lista")
    </div>
</div>

@section Script{
    <script>
        //Máscaras
        $(document).ready(function () {
            $("#Data_entrada").mask("00/00/0000");
            $("#Data_saida").mask("00/00/0000");
            $("#Cep").mask("00000-000");
            $("#Celular").mask("(00)00000-0000");
            $("#Telefonefixo").mask("(00)0000-0000");
        });
        //Função para remover opções
        function removeOptions(selectbox) {
            var i;
            for (i = selectbox.options.length - 1; i >= 0; i--) {
                selectbox.remove(i);
            }
        }

        //Popular placas de veículo quando o cpf é selecionado
        function atualizaPlacas() {
            $.ajax({
                type: "POST",
                url: "/OrdemDeServico/GetPlacas",
                contentType: "application/json; charset=utf-8",
                data: '{"CPF":"' + document.getElementById("listaCpf").value + '"}',
                //dataType: "html",
                success: function (result, status, xhr) {
                    //Declaração de variáveis
                    var select, i, option;
                    select = document.getElementById('listaPlacas');
                    removeOptions(document.getElementById("listaPlacas"));
                    i = 0;
                    //para cada veículo é adicionado a sua respectiva placa
                    result.forEach(function () {
                        option = document.createElement("option");
                        option.text = result[i];
                        select.add(option);
                        i++;
                    });
                },
                error: function (xhr, status, error) {
                    //Mostra mensagem de erro
                    alert("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText);
                }
            });
        }
    </script>
}

Desenvolvimento/WCM/WCM/Views/OrdemDeServico/CadastrarPertence.cshtml
@model WCM.Models.Pertence

@{
    /**/
    ViewBag.Title = "CadastrarPertence";
}

<h2>CadastrarPertence</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pertence</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="field half form-group">
            @Html.LabelFor(model => model.Servico, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" onchange="buscaCod()">
                @Html.DropDownList("listaServicos", "Selecione o serviço")
                @Html.ValidationMessageFor(model => model.Servico, "", new { @class = "text-danger", })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control", Type = "text" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" onclick="cadastrarPertence()" class="btn btn-default" />
            </div>
        </div>
    </div>
    <dl>
        <dt>
            Serviços:
        </dt>
        @foreach (var item in ViewBag.listaServicosDaOrdem)
        {
            <dd>
                @item
            </dd>
        }
    </dl>
}

<div>
    @Html.ActionLink("Voltar para a lista", "Lista")
</div>
@section Script{
    <script>
        //Busca o código do serviço
        function buscaCod() {
            $.ajax({
                type: "POST",
                url: "/OrdemDeServico/BuscarCodServico",
                contentType: "application/json; charset=utf-8",
                data: '{"servico":"' + document.getElementById("listaServicos").value + '"}',
                //dataType: "json",
                success: function (result, status, xhr) {
                },
                error: function (xhr, status, error) {
                    //Mostra um alerta com o erro
                    alert("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText);
                }
            });
        }
        //Cadastra o serviço na OS
        function cadastrarPertence() {
            //alert(document.getElementById("Preco").value);
            $.ajax({
                type: "POST",
                url: "/OrdemDeServico/CadastrarPertenceJS",
                contentType: "application/json; charset=utf-8",
                data: '{"preco":"' + document.getElementById("Preco").value + '"}',
                //dataType: "json",
                success: function (result, status, xhr) {
                },
                error: function (xhr, status, error) {
                }
            });
        }
    </script>
}

Desenvolvimento/WCM/WCM/Views/OrdemDeServico/Detalhes.cshtml
@model WCM.Models.OrdemDeServico

@{
                /**/

                ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <h4>OrdemDeServico</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ordem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ordem)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cpf)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tanque)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tanque)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Km_rodados)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Km_rodados)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_entrada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_entrada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data_saida)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data_saida)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Placa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Placa)
        </dd>

    </dl>
</div>
<dl>
    @*Lista os serviços que fazem parte da OS*@
    <dt>
        Serviços:
    </dt>
    @foreach (var item in ViewBag.listaServicosDaOrdem)
    {
        <dd>
            @item
        </dd>
    }
</dl>
<p>
    @Html.ActionLink("Voltar para a lista", "Lista")
</p>

Desenvolvimento/WCM/WCM/Views/OrdemDeServico/Lista.cshtml
@model IEnumerable<WCM.Models.OrdemDeServico>

@{
    /**/

    ViewBag.Title = "Lista";
}
<div class="inner">
    <h2>Lista de Ordem de Serviço</h2>

    <p>
        @Html.ActionLink("Cadastrar", "Cadastrar")
        @Html.ActionLink("Buscar", "Buscar", "OrdemDeServico")
    </p>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ordem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tanque)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Km_rodados)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data_entrada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data_saida)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Placa)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cpf)
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Ordem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tanque)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Km_rodados)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data_entrada)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Data_saida)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Placa)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cpf)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", "OrdemDeServico", new { id = item.Ordem + "/" }, null) |
                    @Html.ActionLink("Detalhes", "Detalhes", "OrdemDeServico", new { id = item.Ordem + "/" }, null) |
                    @Html.ActionLink("Adicionar serviço", "CadastrarPertence", "OrdemDeServico", new { id = item.Ordem + "/" }, null) |
                    @Html.ActionLink("Excluir", "Excluir", "OrdemDeServico", new { id = item.Ordem + "/" }, null)

                </td>
            </tr>
        }

    </table>
</div>
@section Script{
    <script>
        //function buscaOrdem() {
        //    $.ajax({
        //        type: "POST",
        //        url: "/OrdemDeServico/BuscarOrdem",
        //        contentType: "application/json; charset=utf-8",
        //        data: '{"ordem":"' + document.getElementById("campoBusca").value + '"}',
        //        //dataType: "html",
        //        success: function (result, status, xhr) {
        //            alert("Result: " + result + " //Status: " + status + " //xhr: " + xhr);
        //            for (var item in result) {
        //                alert(item);
        //            }
        //        },
        //        error: function (xhr, status, error) {
        //            alert("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText);
        //        }
        //    });
        //}
    </script>
}