Desenvolvimento/WCM/WCM/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WCM.Models;

namespace WCM.Controllers
{
    public class UsuarioController : Controller
    {
        //Retorna cidades do estado que foi passado
        public JsonResult GetCidades(string UF)
        {
            return Json(Cidade.buscaCidades(UF), JsonRequestBehavior.AllowGet);
        }
        //Tela de cadastro
        public ActionResult Cadastrar()
        {
            ViewBag.listaCidades = new SelectList(Cidade.buscaCidades("AC"));
            ViewBag.listaEstados = new SelectList(Cidade.getEstados());
            if (Session["Login"] != null && (Session["Login"].ToString() == "Funcionário" || Session["Login"].ToString() == "Administrador"))
                return View();
            else
                return RedirectToAction("Index", "Home");
        }
        [HttpPost]//Cadastrar
        public ActionResult Cadastrar(Usuario usuario, string listaCidades, string listaEstados)
        {
            usuario.Cidade = listaCidades;
            usuario.Estado = listaEstados;
            //Testa todas as validações e cadastra o usuário caso esteja tudo ok
            if (usuario.validaEmail() && usuario.validaCpf().Equals("CPF Válido"))
            {
                if (usuario.TipoUsuario != "Cliente")
                {
                    if (usuario.Senha != null)
                    {
                        TempData["Msg"] = usuario.Inserir();
                        if (Session["Login"] != null && (Session["Login"].ToString() == "Funcionário" || Session["Login"].ToString() == "Administrador"))
                            return RedirectToAction("Lista");
                        else
                            return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        TempData["Msg"] = "É obrigatório preencher o campo senha ao cadastrar Funcionários ou Administradores";
                        ViewBag.listaCidades = new SelectList(Cidade.buscaCidades("AC"));
                        ViewBag.listaEstados = new SelectList(Cidade.getEstados());
                        if (Session["Login"] != null && (Session["Login"].ToString() == "Funcionário" || Session["Login"].ToString() == "Administrador"))
                            return View("Cadastrar", usuario);
                        else
                            return RedirectToAction("Index", "Home");
                    }
                }
                else
                    TempData["Msg"] = usuario.Inserir();
                if (Session["Login"] != null && (Session["Login"].ToString() == "Funcionário" || Session["Login"].ToString() == "Administrador"))
                    return RedirectToAction("Lista");
                else
                    return RedirectToAction("Index", "Home");
            }
            else if (usuario.validaCpf().Equals("CPF Válido"))
            {
                TempData["Msg"] = "Email inválido";
                ViewBag.listaCidades = new SelectList(Cidade.buscaCidades("AC"));
                ViewBag.listaEstados = new SelectList(Cidade.getEstados());
                if (Session["Login"] != null && (Session["Login"].ToString() == "Funcionário" || Session["Login"].ToString() == "Administrador"))
                    return View("Cadastrar", usuario);
                else
                    return RedirectToAction("Index", "Home");
            }
            else
            {
                TempData["Msg"] = usuario.validaCpf();
                if (Session["Login"] != null && (Session["Login"].ToString() == "Funcionário" || Session["Login"].ToString() == "Administrador"))
                    return RedirectToAction("Cadastrar");
                else
                    return RedirectToAction("Index", "Home");
            }
        }
        //Lista os usuários conforme o nível de acesso
        public ActionResult Lista()
        {
            string tipoUsuario = "";
            if (Session["Login"] != null)
            {
                if (Session["Login"].ToString().Equals("Funcionário"))
                    tipoUsuario = "Cliente";
                if (Session["Login"].ToString().Equals("Administrador"))
                    tipoUsuario = "";
                return View("Lista", Models.Usuario.ListaUsuario(tipoUsuario));
            }
            else
                return RedirectToAction("Index", "Home");
        }
        //Tela editar
        public ActionResult Editar(string id)
        {
            Usuario usuario = Usuario.BuscaUsuarios(id);
            ViewBag.listaCidades2 = new SelectList(Cidade.buscaCidades(usuario.Estado));
            ViewBag.listaEstados2 = new SelectList(Cidade.getEstados());
            if (Session["Login"] != null && (Session["Login"].ToString() == "Funcionário" || Session["Login"].ToString() == "Administrador"))
                return View("Editar", usuario);
            else
                return RedirectToAction("Index", "Home");
        }
        [HttpPost]//editar
        public ActionResult Editar(Usuario usuario, string listaCidades2, string listaEstados2)
        {
            usuario.Cidade = listaCidades2;
            usuario.Estado = listaEstados2;
            TempData["Msg"] = usuario.Editar();
            if (Session["Login"] != null && (Session["Login"].ToString() == "Funcionário" || Session["Login"].ToString() == "Administrador"))
                return RedirectToAction("Lista");
            else
                return RedirectToAction("Index", "Home");
        }
        //tela de excluir
        public ActionResult Excluir(string id)
        {
            TempData["id"] = id;
            if (Session["Login"] != null && (Session["Login"].ToString() == "Funcionário" || Session["Login"].ToString() == "Administrador"))
                return View(Usuario.BuscaUsuarios(id));
            else
                return RedirectToAction("Index", "Home");
        }
        [HttpPost]//excluir
        public ActionResult Excluir()
        {
            if (TempData["id"] != null)
            {
                Usuario usuario = new Usuario();
                usuario.Cpf = TempData["id"].ToString();
                usuario.Excluir();
            }
            if (Session["Login"] != null && (Session["Login"].ToString() == "Funcionário" || Session["Login"].ToString() == "Administrador"))
                return RedirectToAction("Lista");
            else
                return RedirectToAction("Index", "Home");
        }
        //Tela de detalhes do usuário
        public ActionResult Detalhes(string id)
        {
            //busca as placas dos veículos do usuário
            ViewBag.listaPlacas = new SelectList(Veiculo.buscaVeiculosDoUsuario(id));
            if (Session["Login"] != null && (Session["Login"].ToString() == "Funcionário" || Session["Login"].ToString() == "Administrador"))
                return View("Detalhe", Usuario.BuscaUsuarios(id));
            else
                return RedirectToAction("Index", "Home");
        }
        //Busca os dados de um veículo
        public JsonResult GetVeiculo(string id)
        {
            Veiculo veiculo = new Veiculo();
            veiculo.Placa = id;
            veiculo = veiculo.BuscaVeiculo();
            var resultado = new
            {
                ano = veiculo.Ano,
                cor = veiculo.Cor,
                marca = veiculo.Marca,
                modelo = veiculo.Modelo,
                motor = veiculo.Motor
            };
            return Json(resultado);
        }
    }
}

Desenvolvimento/WCM/WCM/Controllers/VeiculoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WCM.Models;

namespace WCM.Controllers
{
    public class VeiculoController : Controller
    {
        //tela de cadastro
        public ActionResult Cadastrar(string id)
        {
            TempData["CPF"] = id;
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return View();
            else
                return RedirectToAction("Index", "Home");
        }
        [HttpPost]//cadastrar
        public ActionResult Cadastrar(Veiculo veiculo)
        {
            veiculo.FkUsuario = TempData["CPF"].ToString();
            TempData["Msg"] = veiculo.Inserir();
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
                return RedirectToAction("Lista", "Usuario");
            else
                return RedirectToAction("Index", "Home");
        }
        //Passando os atributos para editar os veiculos
        [HttpPost]
        public ActionResult Editar(string placa, string modelo, string cor, string marca, string motor, string fkUsuario)
        {
            Veiculo m = new Veiculo();
            m.Placa = placa;
            m.Modelo = modelo;
            m.Cor = cor;
            m.Marca = marca;
            m.Motor = motor;
            m.FkUsuario = fkUsuario;

            string res = m.Editar();
            TempData["Msg"] = res;
            if (Session["Login"] != null && Session["Login"].ToString() == "Funcionário")
            {
                if (res == "Salvo com sucesso!")
                    return RedirectToAction("Editar");
                else
                    return View();
            }
            else
                return RedirectToAction("Index", "Home");
        }
    }
}

Desenvolvimento/WCM/WCM/Views/Usuario/Cadastrar.cshtml
@model WCM.Models.Usuario

@{
    /**/

    ViewBag.Title = "Cadastrar";
}

<div class="inner" onload="hidePasswordInput()">
    <br />
    <h2>Cadastrar Usuários</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal fields">
            <hr />
            <div class="field half form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10" onchange="atualizaCidades()">
                    @Html.DropDownList("listaEstados")
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger", })
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="field half form-group">
                @Html.LabelFor(model => model.Cpf, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Cpf, new { htmlAttributes = new { @class = "form-control", minlength = "14", maxlength = "14" } })
                    @Html.ValidationMessageFor(model => model.Cpf, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("listaCidades")
                    @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control", minlength = "13", maxlength = "14" } })
                    @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.Cep, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Cep, new { htmlAttributes = new { @class = "form-control", minlength = "9", maxlength = "9" } })
                    @Html.ValidationMessageFor(model => model.Cep, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.Telefonefixo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Telefonefixo, new { htmlAttributes = new { @class = "form-control", minlength = "13", maxlength = "14" } })
                    @Html.ValidationMessageFor(model => model.Telefonefixo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control", @type = "text" } })
                    @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="field half form-group">
                @Html.LabelFor(model => model.TipoUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <select name="TipoUsuario" onchange="tipoUsuarioAlterado()" id="TipoUsuario">
                        <option id="TipoUsuario">...</option>
                        <option id="TipoUsuario">Cliente</option>
                        @if (Session["Login"] != null && Session["Login"].Equals("Administrador"))
                        {
                            <option id="TipoUsuario">Funcionário</option>
                            <option id="TipoUsuario">Administrador</option>
                        }
                    </select>
                    @Html.ValidationMessageFor(model => model.TipoUsuario, "", new { @class = "text-danger" })
                </div>
            </div>
            @if (Session["Login"] != null && Session["Login"].Equals("Administrador"))
            {
                <div class="field half form-group" id="Senha">
                    @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.PasswordFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control", minlength = "6", maxlength = "20" } })
                        @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                    </div>
                </div>
            }

            <br />

            <div class="field half form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Cadastrar" class="btn btn-default" />
                    @*<input type="button" href="~/Home2/Index2" value="Voltar" class="btn btn-default" />*@
                </div>
            </div>

        </div>

    }
    <div>
        @Html.ActionLink("Voltar", "Lista")
    </div>
</div>
@section Script{
    <script>
        //Máscara
        $(document).ready(function () {
            $("#Cpf").mask("000.000.000-00");
            $("#Cep").mask("00000-000");
            $("#Celular").mask("(00)00000-0000");
            $("#Telefonefixo").mask("(00)0000-0000");
        });

        //Função para remover opções
        function removeOptions(selectbox) {
            var i;
            for (i = selectbox.options.length - 1; i >= 0; i--) {
                selectbox.remove(i);
            }
        }

        ////Popular cidades quando o estado é selecionado
        function atualizaCidades() {
            $.post("GetCidades", { UF: document.getElementById('listaEstados').value }, function (data) {
                var select, i, option;
                select = document.getElementById('listaCidades');
                removeOptions(document.getElementById("listaCidades"));

                i = 0;
                data.forEach(function () {
                    option = document.createElement("option");
                    option.text = data[i];
                    select.add(option);
                    i++;
                });
            });
        }
        //Quando o usuário selecionado é um cliente é escondido o campo senha, do contrário ele é exibido
        function tipoUsuarioAlterado() {
            var tipoUsuario = document.getElementById("TipoUsuario").value;
            var senha = document.getElementById("Senha");
            //alert("tipo de usuario: " + tipoUsuario);

            if (tipoUsuario != "Cliente") {
                //alert("entrou no if, usuario: " + tipoUsuario);
                senha.style.display = 'block';
            } else {
                //alert("entrou no else, usuario: " + tipoUsuario);
                senha.style.display = 'none';
            }
        }

        $(document).ready(function () {
            $('#Esconder').delay(20000).fadeOut();
        });
    </script>
}

Desenvolvimento/WCM/WCM/Views/Usuario/Detalhe.cshtml
@model WCM.Models.Usuario
@{
    /**/

    ViewBag.Title = "Detalhe";
}
<div class="inner">
    <h2>Detalhes do Usuário</h2>
    <div>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nome)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Celular)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Telefonefixo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ativo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cpf)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TipoUsuario)
                </th>
            </tr>
            <tr>

                <td>
                    @Html.DisplayFor(model => model.Nome)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Celular)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Telefonefixo)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Ativo)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Cpf)
                </td>
                <td>
                    @Html.DisplayFor(model => model.TipoUsuario)
                </td>
            </tr>
        </table>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Endereco)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cep)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cidade)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Estado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Senha)
                </th>


                <th>
                    @Html.DisplayNameFor(model => model.Bairro)
                </th>

            </tr>
            <tr>
                <td>
                    @Html.DisplayFor(model => model.Endereco)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Cep)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Cidade)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Estado)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Email)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Senha)
                </td>

                <td>
                    @Html.DisplayFor(model => model.Bairro)
                </td>

            </tr>
        </table>
        @*Select com as placas dos veículos do Usuário*@
        <div onchange="atualizaVeiculo()">
            @Html.DropDownList("listaPlacas", "Selecione a placa")
        </div>
        <br />

        <table class="table">
            <tr>
                <th>
                    Ano
                </th>

                <th>
                    Cor
                </th>

                <th>
                    Marca
                </th>

                <th>
                    Modelo
                </th>

                <th>
                    Motor
                </th>
            </tr>
            <tr>
                <td id="ano"></td>
                <td id="cor"></td>
                <td id="marca"></td>
                <td id="modelo"></td>
                <td id="motor"></td>
            </tr>
        </table>

    </div>
    <p>
        @Html.ActionLink("Editar", "Editar", new { id = Model.Cpf + "/" }) |
        @Html.ActionLink("Cadastrar carro", "Cadastrar", "Veiculo", new { id = Model.Cpf + "/" }, null) |
        @Html.ActionLink("Voltar para a lista", "Lista")
    </p>
</div>
@section Script{
    <script>

        //Função para remover opções
        function removeOptions(selectbox) {
            var i;
            for (i = selectbox.options.length - 1; i >= 0; i--) {
                selectbox.remove(i);
            }
        }

        ////Popular dados do véiculo quando a placa é selecionada
        function atualizaVeiculo() {
            $.ajax({
                type: "POST",
                url: "/Usuario/GetVeiculo",
                contentType: "application/json; charset=utf-8",
                data: '{"id":"' + document.getElementById("listaPlacas").value + '"}',
                //dataType: "html",
                success: function (result, status, xhr) {
                    //declaração de variáveis
                    var ano, cor, marca, modelo, motor;
                    //Pegando endereço dos elementos da página
                    ano = document.getElementById("ano");
                    cor = document.getElementById("cor");
                    marca = document.getElementById("marca");
                    modelo = document.getElementById("modelo");
                    motor = document.getElementById("motor");
                    //Populando os mesmos com os dados
                    ano.innerText = result.ano;
                    cor.innerText = result.cor;
                    marca.innerText = result.marca;
                    modelo.innerText = result.modelo;
                    motor.innerText = result.motor;

                },
                error: function (xhr, status, error) {
                    //Alerta de erro
                    alert("Result: " + status + " // " + error + " // " + xhr.status + " // " + xhr.statusText + " // " + xhr.s);
                }
            });
        }
    </script>
}

Desenvolvimento/WCM/WCM/Views/Usuario/Excluir.cshtml
@model WCM.Models.Usuario

@{
    /**/

    ViewBag.Title = "Excluir";
}
<div class="inner">
    <h2>Excluir Usuários</h2>

    <h3>Você tem certeza que deseja apagar este usuário?</h3>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Celular)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefonefixo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ativo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoUsuario)
            </th>
        </tr>
        <tr>

            <td>
                @Html.DisplayFor(model => model.Nome)
            </td>
            <td>
                @Html.DisplayFor(model => model.Celular)
            </td>

            <td>
                @Html.DisplayFor(model => model.Telefonefixo)
            </td>

            <td>
                @Html.DisplayFor(model => model.Ativo)
            </td>

            <td>
                @Html.DisplayFor(model => model.Cpf)
            </td>
            <td>
                @Html.DisplayFor(model => model.TipoUsuario)
            </td>
        </tr>
    </table>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Endereco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cep)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Senha)
            </th>


            <th>
                @Html.DisplayNameFor(model => model.Bairro)
            </th>

        </tr>
        <tr>
            <td>
                @Html.DisplayFor(model => model.Endereco)
            </td>

            <td>
                @Html.DisplayFor(model => model.Cep)
            </td>

            <td>
                @Html.DisplayFor(model => model.Cidade)
            </td>

            <td>
                @Html.DisplayFor(model => model.Estado)
            </td>

            <td>
                @Html.DisplayFor(model => model.Email)
            </td>

            <td>
                @Html.DisplayFor(model => model.Senha)
            </td>

            <td>
                @Html.DisplayFor(model => model.Bairro)
            </td>

        </tr>
    </table>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Lista")
        </div>
    }

</div>

Desenvolvimento/WCM/WCM/Views/Usuario/Lista.cshtml
@model IEnumerable<WCM.Models.Usuario>

@{
    /**/

    ViewBag.Title = "Usuário";
}

@if (TempData["Msg"] != null)
{
    if (TempData["Msg"].ToString().Equals("Inserido com sucesso!"))
    {
        <div id="Esconder" style="text-align:center; background-color: aquamarine"> @TempData["Msg"] </div>
    }
    else
    {
        <div id="Esconder" style="text-align:center; background-color: red"> @TempData["Msg"] </div>
    }
}

<div class="inner">
    <h2>Listar Usuários</h2>
    <p>
        @Html.ActionLink("Cadastre um Novo", "Cadastrar")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Celular)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefonefixo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoUsuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bairro)
            </th>
            <th>
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cpf)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Celular)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefonefixo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoUsuario)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Bairro)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", "Usuario", new { id = item.Cpf + "/" }, null) |
                    @Html.ActionLink("Detalhes", "Detalhes", "Usuario", new { id = item.Cpf + "/" }, null) |
                    @Html.ActionLink("Excluir", "Excluir", "Usuario", new { id = item.Cpf + "/" }, null) |
                </td>
            </tr>
        }
    </table>
</div>

@section Script{
    <script>
        $(document).ready(function () {
            $('#Esconder').delay(20000).fadeOut();
        });
    </script>
}